### ISSUE TITLE
2019-05-01 개발일지

### ISSUE THREAD

**Issue by taeuk-gang** [capstone-willson/chatbot-front#10]
- ## 오늘의 목표
  ```
  새벽(1~6)
  # 한양 챗봇 - 학식관련 DB 환경구축/ 기능 구현
  ```
  ```
  오전(6~12)
  # 한양 챗봇 - 학식관련 DB 환경구축/ 기능 구현(2)
  ```
  ```
  오후(13~18)
  # 한양 챗봇 - 학식관련 DB 환경구축/ 기능 구현(3)
  ```
  ```
  저녁(18~24)
  # 한양 챗봇 - 안드로이드 어플 플랫폼 개발
  ```
  ## 진행내용

  **새벽(1~6)**

  > node.js 서버 안 몽고DB · 몽구스 모듈 설치 및 환경 설정
  >
  > <img src="https://user-images.githubusercontent.com/26294469/57001757-6a887c80-6bf5-11e9-8f4c-6b3627b6fb75.png">

  > /hanyangfoods 라우팅 설정 변경 

  **오전(6~12)**

  > node.js 스케줄링 - 00:00 마다 오늘의 학식 데이터 DB에 크롤링하여 저장
  >
  > <img src="https://user-images.githubusercontent.com/26294469/57004741-5ac86280-6c0c-11e9-95b2-5c7f341b163f.png" >

  **오후(12~18)**

  > Node.js 서버 API - Swagger간 연결을 통하여 API 문서화
  >
  > <img src="https://user-images.githubusercontent.com/26294469/57011460-b6aadf80-6c3c-11e9-96cd-00480379a30a.png" > 

  > <img src="https://user-images.githubusercontent.com/26294469/57011482-d2ae8100-6c3c-11e9-94ed-0861d551d23f.png" >

  **저녁(18~24)**

  > 한양 챗봇 - 안드로이드 어플 APK 파일 패키징
  >
  > <img src="https://user-images.githubusercontent.com/26294469/57013771-0642d880-6c48-11e9-943e-8474e64eebe3.png" width="200px" >
  >
  > 

  ## 다음날 전달사항

  -

**Comment by rhodochrosite** [comment]
😨😨😨 리얼루 일지잖어.. 👍👍👍
